---
- name: Get latest version
  uri:
    url: https://github.com/jesseduffield/lazydocker/releases/latest
    return_content: yes
    body_format: json
    headers:
      Accept: application/json
  register: version

- name: Download archive
  vars:
    release_version: "{{ version.json.tag_name }}"
    release_file_name: "lazydocker_{{ version.json.tag_name | replace('v','')}}_Linux_{{ ansible_architecture}}.tar.gz"
  get_url:
    url: "https://github.com/jesseduffield/lazydocker/releases/download/{{ release_version }}/{{ release_file_name }}"
    dest: "/tmp/lazydocker.tar.gz"
  when: ansible_local['lazydocker'] is not defined or ansible_local['lazydocker']['general']['version'] != version.json.tag_name

- name: Create ~/.local directory if does not exist yet
  file:
    path: "{{ ansible_user_dir}}/.local/bin"
    state: directory

- name: Extract archive
  become: true
  unarchive:
    src: "/tmp/lazydocker.tar.gz"
    remote_src: yes
    dest: "{{ ansible_user_dir}}/.local/bin"
  when: ansible_local['lazydocker'] is not defined or ansible_local['lazydocker']['general']['version'] != version.json.tag_name

- name: Create facts directory
  become: true
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory

- name: Set fact
  become: true
  ansible.builtin.template:
    src: lazydocker.fact.j2
    dest: /etc/ansible/facts.d/lazydocker.fact
