- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        force_apt_get: yes
        update_cache: yes
        state: present
      tags:
        - install
        - core
  tasks:
    - name: Core Setup
      include_tasks: tasks/core-setup.yml
      tags:
        - install
        - core
    - name: Install Neovim
      include_tasks: tasks/neovim.yml
      tags:
        - install
        - neovim
    - name: Install Starship Prompt
      include_tasks: tasks/starship.yml
      tags:
        - install
        - starship
    - name: Install Node Version Manager
      include_tasks: tasks/nvm.yml
      tags:
        - install
        - node
    - name: Install PHP
      include_tasks: tasks/php.yml
      tags:
        - php
    - name: Install Docker
      include_tasks: tasks/docker.yml
      tags:
        - docker
    - name: Install Github CLI
      include_tasks: tasks/gh.yml
      tags:
        - gh
