---
- name: Install git
  become: true
  ansible.builtin.package:
    name: git
    state: latest

- name: Set user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Set user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Set detaul branch name
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
