---
- name: Add VirtualBox GPG key
  become: true
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/virtualbox-archive-keyring.gpg

- name: Add VirtualBox apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release | lower }} contrib"
    state: present

- name: Install VirtualBox
  become: true
  ansible.builtin.package:
    name: virtualbox-6.1
    state: latest
