---
- name: Add HashiCorp GPG key
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repository
  become: true
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present

- name: Install terraform
  become: true
  ansible.builtin.package:
    name: terraform
    state: latest
