---
- name: Add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg

- name: Add Docker apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present

- name: Install Docker
  become: true
  ansible.builtin.package:
    name: 
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - "docker-compose-plugin"
    state: latest
